name = "Mealy"
version = "0.1.0"
defaultTargets = ["mealy"]

[[lean_lib]]
name = "Mealy"

[[lean_exe]]
name = "mealy"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "«lean-fmt»"
git = "https://github.com/jcreinhold/lean-fmt"
rev = "v4.34.0-rc2"