#import "@preview/mmdr:0.2.2": mermaid
#import "@preview/fletcher:0.5.8" as fletcher: diagram, edge, node
#import "@preview/codly:1.3.0"
#import "@preview/curryst:0.6.0": prooftree, rule, rule-set
#import "@preview/acrostiche:0.7.0": *
#import "@preview/theoretic:0.4.0"
#import theoretic.presets.basic: * // this will automatically load predefined styled environments
#show ref: theoretic.show-ref      // this is necessary for references to theorems to work

#import "@preview/cetz:0.5.2"
#show ref: theoretic.show-ref      // this is necessary for references to theorems to work


// a Mealy machine drawn as a box
#let mbox = (pos, lbl) => node(pos, lbl, shape: fletcher.shapes.rect, stroke: .6pt, inset: 9pt)
#let compbox = enc => node(enclose: enc, stroke: (paint: gray, dash: "dashed", thickness: .6pt), inset: 16pt)

#let fltl4 = `FLTL₄`


#set document(title: [Reactor: a #fltl4 monitor])


#show heading.where(level: 1): set heading(numbering: "1")


#set page(
  numbering: "1",
  number-align: center + bottom, // Places number in the header
)

#set par(justify: true, first-line-indent: 1.5em)

#init-acronyms((
  "RV": ("Runtime Verification", "Runtime Verifications"),
))

#title()

// ---------- palette ----------
#let cteal = rgb("#1D9E75")
#let ctealD = rgb("#0F6E56")
#let camber = rgb("#EF9F27")
#let camberD = rgb("#B26E0A")
#let cred = rgb("#E24B4A")
#let credD = rgb("#A32D2D")
#let cpurp = rgb("#7F77DD")
#let cpurpD = rgb("#534AB7")
#let cgray = rgb("#5F5E5A")
#let caxis = rgb("#888780")
// ---------- end palette ----------

// ---------- diagram kit ----------
#let dfont = ("Avenir Next", "Helvetica Neue")

#let dtext(fill: cgray, size: .85em, weight: "medium", body) = text(
  font: dfont,
  size: size,
  fill: fill,
  weight: weight,
  body,
)

// a soft, rounded, tinted node
#let sbox = (pos, body, hue, ..args) => node(
  pos,
  body,
  shape: fletcher.shapes.rect,
  fill: hue.lighten(88%),
  stroke: hue.darken(12%) + .9pt,
  corner-radius: 6pt,
  inset: 10pt,
  ..args,
)

// an edge label
#let elbl = (body, col) => dtext(fill: col, size: .78em, body)

// one truth value of B₄: a mark (polarity) over its symbol; hue = certainty,
// full size = definitive verdict, smaller = presumable one
#let vmark = (mark, col, lbl, size: 1.15em) => stack(
  dir: ttb,
  spacing: .32em,
  text(fill: col, size: size, mark),
  text(font: dfont, size: .62em, fill: col.darken(8%), lbl),
)
// an observed event on a trace timeline
#let tdot = (pos, ..args) => node(pos, none, shape: circle, radius: 3.2pt, fill: cgray, stroke: none, ..args)

// a state that has not been observed (beyond the end of the trace)
#let gdot = (pos, ..args) => node(
  pos,
  none,
  shape: circle,
  radius: 3.2pt,
  fill: white,
  stroke: caxis + .8pt,
  ..args,
)

// a verdict reached by one possible continuation, with a gloss
#let vpill = (pos, sym, hue, note, ..args) => node(
  pos,
  stack(
    dir: ltr,
    spacing: .6em,
    text(fill: hue.darken(12%), size: 1em, sym),
    dtext(fill: caxis, size: .72em, note),
  ),
  fill: hue.lighten(92%),
  stroke: hue.darken(12%) + .8pt,
  corner-radius: 5pt,
  inset: 7pt,
  ..args,
)
// ---------- end diagram kit ----------

#let sem(x) = $lr(⟦ #x ⟧)_4$ // semantic bracket  ⟦ … ⟧₄
#let semw(x) = $lr(⟦ #x ⟧)_ω$ // semantic bracket ⟦ … ⟧_ω : LTL over infinite traces
#let semf(x) = $lr(⟦ #x ⟧)_F$ // semantic bracket ⟦ … ⟧_F : FLTL over finite traces

// the small bold rubric heading a group of equations inside a semantics figure
#let fgrp = body => text(weight: "bold", size: .95em, body)

// a `cases` branch whose verdict is held vertically centred against a
// multi-line side condition
#let mcase = (verdict, ..rows) => box(grid(
  columns: (auto, auto),
  column-gutter: .6em,
  align: (horizon, left + horizon),
  verdict, grid(columns: 1, row-gutter: .75em, align: left, ..rows.pos()),
))

// the matching single-line branch, indented to line up with `mcase`
#let scase = (verdict, body) => box(grid(
  columns: (auto, auto),
  column-gutter: .6em,
  align: left,
  verdict, body,
))



= Context

#acr("RV") @Bartocci2018IntroductionTR is a lightweight (yet rigorous) method that complements classical exhaustive verification techniques (such as model checking and theorem proving) with a more practical approach and try to be closer to the actual real system.
RV works by analyzing the trace of the system's actual execution, comparing it against a formal specification of the system behavior.
This task is perform by a _monitor_ (cf. @fig-rv-loop) that run alongside a system to observe its behavior and determine if it satisfies a specified correctness property.
The main advantage using RV can give precise information on the runtime behavior of the monitored system, without the pitfalls of developing models that require a re-implementation of the entire system in a modeling language.

Monitors can be classified as _offline_ and _online_ monitors @taxonomy-rv.
Offline monitor @tla-rv process the traces generated by a system after the events, generally by reading the trace execution from a permanent storage system.
Online monitors process the trace during the execution of the system. Online monitors are said to be synchronous if the processing of an event is attached to the system execution, blocking the system during the event monitoring.
On the other hand, an asynchronous monitor has its execution detached from the system.
Each type of monitor has a set of advantages. For example, offline monitors can be executed on different machines but require operations to save the log to a file.
In contrast, synchronous online method can react at the exact moment a violation occurs.

This document aims to specify the development of Reactor -- a online monitor to verify if program guarantee some
temporal assertions defined in the Finite Temporal Linear Logic 4 (FLTL4) @rv-ltl@ltl-book, a suitable temporal logic for RV @rv-ltl.
A `monitor` is created from a  FLTL4 `property`. The monitor is an Mealy machine equivalent to the property.
This is possible because all FLTL4 formulas can be transformed into a Mealy machine @rv-ltl.


#figure(
  placement: bottom,
  diagram(
    spacing: (5.2em, 4.2em),
    node-outset: 2pt,

    // ── property ──────────────────────────────────────────────
    node(
      (0, 0),
      stack(
        dir: ttb,
        spacing: 1em,
        dtext(fill: cpurpD, weight: "bold")[property],
        text(size: .9em, fill: cpurpD, $tack.r space square (A -> diamond B)$),
      ),
      shape: fletcher.shapes.ellipse,
      fill: cpurp.lighten(90%),
      stroke: cpurpD + .9pt,
      inset: 12pt,
      name: <prop>,
    ),

    // ── monitor ───────────────────────────────────────────────
    sbox((0, 1), dtext(fill: ctealD, weight: "bold")[monitor], cteal, name: <mon>),

    // ── verdict ───────────────────────────────────────────────
    node(
      (1.15, 1),
      stack(
        dir: ltr,
        spacing: .7em,
        emoji.checkmark,
        "|",
        emoji.crossmark,
      ),
      fill: white,
      stroke: cgray + .9pt,
      corner-radius: 6pt,
      inset: 9pt,
      name: <verd>,
    ),

    // ── instrumentation ∙ system ──────────────────────────────
    sbox(
      (0, 2.15),
      stack(
        dir: ttb,
        spacing: .45em,
        text(size: 1.45em, emoji.gear),
        dtext(fill: cgray.darken(20%), weight: "bold")[System],
      ),
      cgray,
      name: <sys>,
    ),
    node((0, 2.62), dtext(fill: caxis, size: .74em)[Instrumentation], name: <ilbl>),
    node(
      enclose: (<sys>, <ilbl>),
      inset: 12pt,
      stroke: (paint: caxis, dash: "dashed", thickness: .7pt),
      corner-radius: 8pt,
      name: <instr>,
    ),

    // ── wiring ────────────────────────────────────────────────
    edge(<prop>, <mon>, "->", stroke: cpurpD + .7pt),
    edge(<mon>, <instr>, "->", elbl([Feedback], caxis), shift: 9pt, label-side: left, stroke: caxis + .7pt),
    edge(<instr>, <mon>, "->", elbl([Observe], caxis), shift: 9pt, label-side: left, stroke: caxis + .7pt),
    edge(<mon>, <verd>, "->", elbl([Verdict], caxis), label-side: left, stroke: caxis + .7pt),
  ),
  caption: [The runtime-verification loop],
) <fig-rv-loop>

== Overview

The rest of this document is organised as follows:
- @sec-prelim fixes the notation used throughout.
- @sec-fltl4 presents the #fltl4 logic: the maxims a semantics for runtime verification must
respect, the syntax of #fltl4 over the four-valued domain $bb(B)_4$, its semantics,
and the Mealy machine a formula is compiled into.
- @sec-dev describes the implementation of the `monitor` built from these machines.

= Preliminaries <sec-prelim>

== Traces

For the remainder of this article, let $bold("AP")$ be a finite and non-empty set of atomic propositions and
$Σ=2^bold("AP")$ a finite alphabet. We write $a_i$ for any single element of $Σ$, i.e. $a_i$ is a possibly empty subset
of propositions taken from AP. Finite traces (which we call interchangeably words) over $Σ$ are elements of $Sigma^∗$, usually denoted with $u,u',u_1,u_2, dots$. The empty trace is denoted with ϵ. Infinite traces are elements of $Σ^ω$, usually denoted with $w, w', w_1, w_2, dots$ For some infinite trace $w = a_0a_1 ...$, we denote with $w^i$ the suffix $a_i, a_(i+1) dots$ . In case of a finite trace $u=a_0a_1 ...a_(n−1)$, $u^i$ denotes the suffix $a_i a_(i+1) ...a_(n−1)$ for $0 ≤ i < n$ and the empty string ϵ for $n ≤ i$.

== Truth domain

A lattice is a partially ordered set $(cal(L), ⊑)$ where for each $x,y ∈ cal(L)$, there exists (i) a unique greatest
lower bound (glb), which is called the meet of $x$ and $y$, and is denoted with $x ⊓ y$, and (ii) a unique
least upper bound (lub), which is called the join of $x$ and $y$, and is denoted with $x ⊔ y$. A lattice is called
finite iff $L$ is finite. Every finite lattice has a well-defined unique least element, called bottom, denoted
with $⊥$, and analogously a greatest element, called top, denoted with . A lattice is distributive, iff $x ⊓
(y ⊔ z) = (x ⊓ y) ⊔ (x ⊓ z)$, and, dually, $x ⊔ (y ⊓ z)=(x ⊔ y) ⊓ (x ⊔ z)$. In a _de Morgan_ lattice, every element
$x$ has a unique dual element $overline(x)$, such that $overline(overline(x)) = x$ and $x ⊑ y$ implies $overline(y) ⊑ overline(x)$. A distributive lattice is called Boolean iff $x ⊔ overline(x) = ⊤$ and $x ⊓ overline(x) = ⊥$.
As the common denominator of the semantics for the subsequently defined logics is a finite de Morgan lattice, we take this to our understanding of a truth domain.

We consider the traditional two-valued semantics that we denotes $bb(B)_2$ with truth values `true`, denoted with $top$, and `false`, denoted with $bot$. Truth values should be comparable and combinable in terms of Boolean operations expressed by the connectives of the underlying logic, we interpret these truth values as elements of a _de Morgan_ lattice.

#definition("Truth domain", label: <def:truth-dom>)[
  We call $cal(D)$ a _truth domain_, if it is a finite de Morgan lattice. The two valued truth domain $bb(B)_2 = { top, bot}$ is a Boolean lattice with $bot subset.sq top$ and $inter.sq$ and $union.sq$ definedin the expected manner.
]

== LTL and FLTL

we first recall LTL interpreted over infinite traces, as introduced by Pnueli @ltl in the setting of specification and verification.
In case of LTL over infinite traces, one is used to have a syntax ranging over a small set of temporal and Boolean operators and to add additional operators by means of abbreviations.
The set of LTL formulae is defined using _true_, the atomic propositions $p ∈ bold("AP")$, disjunction, _next_ *X* and _until_ *U*, as positive operators, together with _negation_ ¬.
For comparison with logics over finite traces, we moreover add dual operators, namely false, $¬p$, weak next $overline(X)$ and release *R*, respectively.

#definition("Syntax of LTL formulae", label: <def:ltl-syntax>)[
  Let $p$ be an atomic proposition from a finite set of atomic propositions $bold("AP")$. The set of
  LTL formulae, denoted with LTL, is inductively defined by the following grammar:
  $
    φ & ::= "true" | p | φ or φ | φ bold("U") φ | bold(X) φ \
    φ & ::= "false" | ¬p | φ and φ | φ bold("R") φ | overline(bold(X)) φ \
    φ & ::= ¬φ
  $
]

Moreover, we define by means of abbreviation the _finally_ $bold(F)$ and _globally_ $bold(G)$
operators as

$ bold(F) φ := "true" bold("U") φ quad "and" quad bold(G) φ := ¬ bold(F) ¬φ $

as well as _implication_ $φ -> ψ$ as a shorthand for $¬φ or ψ$.
LTL formulae over infinite traces are interpreted as usual over the two valued truth domain
$bb(B)_2$.

#figure(
  placement: top,
  align(center)[
    #grid(
      columns: (auto, auto),
      column-gutter: 2.2em,
      row-gutter: 1.4em,
      align: left,
      [
        #fgrp[Boolean constants]
        $
           semw(w tack.r "true") & = top \
          semw(w tack.r "false") & = bot
        $
      ],
      [
        #fgrp[Boolean combinations]
        $
               semw(w tack.r ¬φ) & = overline(semw(w tack.r φ)) \
           semw(w tack.r φ or ψ) & = semw(w tack.r φ) union.sq semw(w tack.r ψ) \
          semw(w tack.r φ and ψ) & = semw(w tack.r φ) inter.sq semw(w tack.r ψ)
        $
      ],

      [
        #fgrp[atomic propositions]
        $
           semw(w tack.r p) & = cases(
                                top & "if " p in a_0,
                                bot & "if " p in.not a_0
                              ) \
          semw(w tack.r ¬p) & = cases(
                                top & "if " p in.not a_0,
                                bot & "if " p in a_0
                              )
        $
      ],
      [
        #fgrp[(weak) next]
        $
                    semw(w tack.r bold(X) φ) & = semw(w^1 tack.r φ) \
          semw(w tack.r overline(bold(X)) φ) & = semw(w^1 tack.r φ)
        $
      ],
    )

    #block(width: 100%)[
      #align(left, fgrp[until/release])
      $
        semw(w tack.r φ bold("U") ψ) & = cases(
                                         gap: #.7em,
                                         #mcase(
                                           $top$,
                                           $"there is a " k >= 0 : semw(w^k tack.r ψ) = top " and"$,
                                           $"for all " l " with " 0 <= l < k : semw(w^l tack.r φ) = top$,
                                         ),
                                         #scase($bot$, $"else"$),
                                       ) \
                                     \
        semw(w tack.r φ bold("R") ψ) & = cases(
                                         gap: #.7em,
                                         #mcase(
                                           $top$,
                                           $"for all " k >= 0 : semw(w^k tack.r ψ) = top " or"$,
                                           $"there is a " k >= 0 : semw(w^k tack.r φ) = top " and"$,
                                           $"for all " l " with " 0 <= l <= k : semw(w^l tack.r ψ) = top$,
                                         ),
                                         #scase($bot$, $"else"$),
                                       )
      $
    ]
  ],
  caption: [Semantics of LTL formulae over an infinite traces $w = a_0 a_1 dots ∈ Σ^ω$],
) <fig-ltl-sem>

#definition("Semantics of LTL", label: <def:ltl-sem>)[
  The semantics of LTL formulae over infinite traces $w = a_0 a_1 dots ∈ Σ^ω$ is given by the
  function $lr(⟦ - tack.r - ⟧)_ω : Σ^ω × "LTL" -> bb(B)_2$, which is defined inductively as shown
  in @fig-ltl-sem.
]

Inspecting the semantics, we observe that there is no difference of $bold(X)$ and
$overline(bold(X))$ in LTL over infinite traces. However, $overline(bold(X))$ acts differently
when finite words are considered.

FLTL @rv-ltl is the interpretation of that same syntax (@def:ltl-syntax) over a _finite_ trace,
still in $bb(B)_2$. Its semantics function is constructed like the one for standard LTL but with
two modifications: if a strong next-state operator in some subformula $bold(X) φ$ is referring to
a state beyond the known finite prefix $u$, then this subformula is evaluated to $bot$, regardless
of $φ$. Likewise, a subformula $overline(bold(X)) φ$ always evaluates to $top$ if it refers to a
state beyond $u$. This approach is extended to the definition of the until and release operators.
For example, to satisfy $φ bold("U") ψ$ with a finite word $u$, there must exist a position
satisfying $ψ$ within $u$.

#figure(
  placement: top,
  align(center)[
    #block(width: 100%)[
      #align(left, fgrp[(weak) next])
      $
                  semf(u tack.r bold(X) φ) & = cases(
                                               semf(u^1 tack.r φ) & "if " u^1 != ϵ,
                                               bot & "otherwise"
                                             ) \
                                           \
        semf(u tack.r overline(bold(X)) φ) & = cases(
                                               semf(u^1 tack.r φ) & "if " u^1 != ϵ,
                                               top & "otherwise"
                                             )
      $

      #align(left, fgrp[until/release])
      $
        semf(u tack.r φ bold("U") ψ) & = cases(
                                         gap: #.7em,
                                         #mcase(
                                           $top$,
                                           $"there is a " k ∈ {0, dots n-1} : semf(u^k tack.r ψ) = top " and"$,
                                           $"for all " l " with " 0 <= l < k : semf(u^l tack.r φ) = top$,
                                         ),
                                         #scase($bot$, $"else"$),
                                       ) \
                                     \
        semf(u tack.r φ bold("R") ψ) & = cases(
                                         gap: #.7em,
                                         #mcase(
                                           $top$,
                                           $"for all " k ∈ {0, dots n-1} : semf(u^k tack.r ψ) = top " or"$,
                                           $"there is a " k ∈ {0, dots n-1} : semf(u^k tack.r φ) = top " and"$,
                                           $"for all " l " with " 0 <= l <= k : semf(u^l tack.r ψ) = top$,
                                         ),
                                         #scase($bot$, $"else"$),
                                       )
      $
    ]
  ],
  caption: [Semantics of FLTL formulae over a trace $u = a_0 dots a_(n-1) ∈ Σ^*$],
) <fig-fltl-sem>

#definition("Semantics of FLTL", label: <def:fltl-sem>)[
  Let $u = a_0 dots a_(n-1) ∈ Σ^*$ denote a finite trace of length $n$, with $u != ϵ$. The truth
  value of an FLTL formula $φ$ w.r.t. $u$, denoted with $semf(u tack.r φ)$, is an element of
  $bb(B)_2$ and is inductively defined as follows: Boolean constants, Boolean combinations and
  atomic propositions are defined as for LTL (see @fig-ltl-sem, taking $u$ instead of $w$).
  Until/release and (weak) next are defined as shown in @fig-fltl-sem.
]



= The logic #fltl4 <sec-fltl4>

FLTL interprets LTL formulae over finite traces.
That is the right reading for a _completed_ run of the execution of a program that terminated and that
no more new event are expected. However, it is a wrong approach for runtime verification, where the trace
in hand is a _prefix_ of a run still being produced i.e. the next event has not arrived yet.
Two failures follow:
- the strong next $bold(X) phi$ has to infer;
- and a two-valued verdict can never be provisional.

The second aspect that expose that with only $top$ and $bot$ available, every verdict is final.
A two-valued semantics has to commit after each event even when the run could still go either way.
Take the request/acknowledge property $φ ≡ bold(G) (r -> bold(F) a)$ of @fig-futures. If the prefix
ends on a request $r$, FLTL evaluates $phi$ to $bot$, but it is too early to say that. $bot$ reads as
_the property is violated_, whereas here we are simply still waiting for the acknowledgement $a$,
which may well arrive later. The honest answer is not a definitive false but something weaker:
_false so far_, or _possibly true_.

This is what #fltl4 provides. It keeps the operators of FLTL and its complementation, and changes
one thing only: instead of two truth values it uses four, the domain $bb(B)_4$. Each of $top$ and
$bot$ is split in two, a definitive verdict and a presumable one, so that a monitor can answer
_true (or false) for now_ while leaving room for the rest of the run. The four maxims below say
precisely what we expect from such a semantics.

#figure(
  placement: top,
  stack(
    dir: ttb,
    spacing: 1.4em,
    diagram(
      spacing: (3.2em, 2em),
      node-outset: 0pt,

      // ── the observed prefix u ──────────────────────────────
      tdot((0, 0), name: <h0>),
      tdot((1, 0), name: <h1>),
      tdot((2, 0), name: <h2>),
      edge(<h0>, <h1>, stroke: cgray + 1pt),
      edge(<h1>, <h2>, stroke: cgray + 1pt),
      node((0, .5), dtext(size: .8em, $a_0$)),
      node((1, .5), dtext(size: .8em, $a_1$)),
      node((2, .5), dtext(size: .8em, $a_(n-1)$)),
      node((1, -.95), dtext(size: .78em)[observed prefix $u$]),

      // ── everything past the last letter ────────────────────
      gdot((3, 0), name: <h3>),
      gdot((4, 0), name: <h4>),
      edge(<h2>, <h3>, stroke: (paint: caxis, dash: "dashed", thickness: .8pt)),
      edge(<h3>, <h4>, stroke: (paint: caxis, dash: "dashed", thickness: .8pt)),
      node((3, .5), dtext(fill: caxis, size: .8em, $a_n$)),
      node((4, .5), dtext(fill: caxis, size: .8em, $dots$)),
      node((3.6, -.95), dtext(fill: caxis, size: .78em)[not observed yet]),

      // ── the horizon the strong next falls over ─────────────
      edge((2.5, -1.25), (2.5, .85), stroke: (paint: credD, dash: "densely-dotted", thickness: 1pt)),
      node((2.5, 1.25), dtext(fill: credD, size: .74em)[end of trace]),
    ),
    $
      semf(u tack.r bold(X) φ) = bot quad "and" quad semf(u tack.r overline(bold(X)) φ) = top
      quad "for every " φ, "whenever " u^1 = ϵ
    $,
  ),
  caption: [
    The strong next falls over the end of the trace. FLTL decides $bold(X)$ and
    $overline(bold(X))$ from the position of the horizon alone, so
    $semf(u tack.r bold(X) "true") = bot$ even though every continuation satisfies it.
  ],
) <fig-horizon>

#figure(
  placement: top,
  diagram(
    spacing: (3.4em, 2.1em),
    node-outset: 0pt,

    // ── an observed run of φ ≡ G(r → F a) ───────────────────
    tdot((0, 0), name: <f0>),
    tdot((1, 0), name: <f1>),
    tdot((2, 0), name: <f2>),
    edge(<f0>, <f1>, stroke: cgray + 1pt),
    edge(<f1>, <f2>, stroke: cgray + 1pt),
    node((0, -.55), dtext(size: .82em, $r$)),
    node((1, -.55), dtext(size: .82em, $a$)),
    node((2, -.55), dtext(size: .82em, $r$)),

    // ── the verdict FLTL emits after each event ─────────────
    node((-1, .55), dtext(fill: caxis, size: .74em)[FLTL verdict]),
    node((0, .55), text(fill: credD, size: .95em, $bot$)),
    node((1, .55), text(fill: ctealD, size: .95em, $top$)),
    node((2, .55), text(fill: credD, size: .95em, $bot$)),

    // ── two continuations of the same prefix ────────────────
    vpill((4, -.9), $top$, cteal, [request served], name: <fu>),
    vpill((4, .9), $bot$, cred, [never served], name: <fd>),
    edge(
      <f2>,
      <fu>,
      "-->",
      elbl($dots a dots$, caxis),
      label-side: left,
      stroke: (paint: caxis, dash: "dashed", thickness: .8pt),
    ),
    edge(
      <f2>,
      <fd>,
      "-->",
      elbl($r^ω$, caxis),
      label-side: right,
      stroke: (paint: caxis, dash: "dashed", thickness: .8pt),
    ),
  ),
  caption: [
    $φ ≡ bold(G) (r -> bold(F) a)$ on a run that keeps requesting. The two continuations of the
    same prefix disagree, so no final verdict is warranted -- yet FLTL must pick one, and its
    $bot$ after the trailing $r$ is indistinguishable from an irrecoverable violation.
  ],
) <fig-futures>

== Maxims for Runtime Verification

A semantics meant for monitoring finite, still-growing traces should respect four
maxims.

+ *Existential next.* Saying "$φ$ holds at the next step" presupposes that a next
  step exists — and on a finite trace we may simply have run out of events. The
  logic therefore needs a _strong_ next $bold(X)$, which refuses to hold when the
  trace stops here, alongside the _weak_ next $overline(bold(X))$, which accepts
  it.

+ *Complementation by negation.* Negating a formula must really flip its verdict:
  $not φ$ evaluates to the complement of $φ$'s verdict, and that complement is
  always a _different_ value. No verdict may be its own complement — which is why
  a single "don't know" value will not do, and why the presumable verdicts come in the pair `potentially` $⊤$ / `potentially` $⊥$.

+ *Impartiality.* A monitor must not jump to conclusions. As long as some
  infinite continuation of what we have seen so far would lead to a different
  answer, the trace must not be given a final $⊤$ or $⊥$; the most it may say is
  "true (false) so far".

+ *Anticipation.* Conversely, a monitor must not sit on a conclusion it can
  already draw. The moment every infinite continuation agrees on one verdict, the
  finite trace must already be evaluated to that verdict — there is nothing left
  to wait for.

== Syntax

The four maxims above fix the truth domain: two definitive verdicts, two presumable
ones, and a complementation pairing them so that no verdict is its own complement.

#definition([Truth domain $bb(B)_4$], label: <def:b4>)[
  The truth domain of #fltl4 is the four valued set
  $ bb(B)_4 = { top, top^p, bot^p, bot } $
  where $top$ (resp. $bot$) denotes the definitive verdict _true_ (resp. _false_) and
  $top^p$ (resp. $bot^p$) the presumable verdict _presumably true_ (resp.
  _presumably false_). It is a finite distributive de Morgan lattice
  $(bb(B)_4, subset.sq)$, hence a truth domain in the sense of @def:truth-dom, ordered
  by
  $ bot subset.sq bot^p subset.sq top^p subset.sq top $
  with $inter.sq$ and $union.sq$ the meet and join of that order, and with
  complementation
  $
    overline(top) = bot quad overline(top^p) = bot^p quad overline(bot^p) = top^p quad overline(bot) = top
  $
]

Note that $bb(B)_4$ is _not_ a Boolean lattice: the presumable verdicts satisfy
$top^p union.sq overline(top^p) = top^p union.sq bot^p = top^p != top$, and dually
$bot^p inter.sq overline(bot^p) = bot^p != bot$. This is precisely what lets a monitor
report a verdict that is not yet final.

#definition([Syntax of #fltl4 formulae], label: <def:fltl4-syntax>)[
  Let $Σ = 2^bold("AP")$ be the finite alphabet built over a finite set of atomic
  propositions $bold("AP")$, with $p ∈ bold("AP")$ an atomic proposition and
  $a ∈ Σ$ a letter. The set of #fltl4 formulae is inductively defined by the following
  grammar:
  $
    φ, ψ ::= b | p | ¬ φ | φ and ψ | φ or ψ | bold(X) φ | overline(bold(X)) φ
           | φ bold("U") ψ | φ bold("R") ψ | bold(F) φ | bold(G) φ
    quad "where " b ∈ bb(B)_4
  $
  In contrast to LTL (@def:ltl-syntax), the constants range over the whole of
  $bb(B)_4$, and $bold(F)$ and $bold(G)$ are taken as primitive operators rather than
  as abbreviations.
]

== Semantics

#figure(
  placement: top,
  align(center)[
    #grid(
      columns: (auto, auto),
      column-gutter: 2.2em,
      row-gutter: 1.4em,
      align: left,
      [
        #fgrp[Boolean constants]
        $
           sem(w tack.r "true") & = top \
          sem(w tack.r "false") & = bot
        $
      ],
      [
        #fgrp[Boolean combinations]
        $
               sem(w tack.r ¬φ) & = overline(sem(w tack.r φ)) \
           sem(w tack.r φ or ψ) & = sem(w tack.r φ) union.sq sem(w tack.r ψ) \
          sem(w tack.r φ and ψ) & = sem(w tack.r φ) inter.sq sem(w tack.r ψ)
        $
      ],

      [
        #fgrp[atomic propositions]
        $
           sem(w tack.r p) & = cases(
                               top & "if " p in w_1,
                               bot & "if " p in.not w_1
                             ) \
          sem(w tack.r ¬p) & = cases(
                               top & "if " p in.not w_1,
                               bot & "if " p in w_1
                             )
        $
      ],
      [
        #fgrp[(weak) next]
        $
                    sem(w tack.r bold(X) φ) & = cases(
                                                sem(w^2 tack.r φ) & "if " abs(w) > 1,
                                                bot^p & "else"
                                              ) \
          sem(w tack.r overline(bold(X)) φ) & = cases(
                                                sem(w^2 tack.r φ) & "if " abs(w) > 1,
                                                top^p & "else"
                                              )
        $
      ],
    )

    #block(width: 100%)[
      #align(left, fgrp[until/release])
      $
        sem(w tack.r φ bold("U") ψ) & = union.sq.big_(1 <= i <= abs(w)) (
                                        sem(w^i tack.r ψ) inter.sq inter.sq.big_(1 <= j < i) sem(w^j tack.r φ)
                                      )
                                      union.sq (
                                        bot^p inter.sq inter.sq.big_(1 <= i <= abs(w)) sem(w^i tack.r φ)
                                      ) \
                                    \
        sem(w tack.r φ bold("R") ψ) & = union.sq.big_(1 <= i <= abs(w)) (
                                        sem(w^i tack.r φ) inter.sq inter.sq.big_(1 <= j <= i) sem(w^j tack.r ψ)
                                      )
                                      union.sq (
                                        top^p inter.sq inter.sq.big_(1 <= i <= abs(w)) sem(w^i tack.r ψ)
                                      )
      $

      #align(left, fgrp[finally/globally])
      $
        sem(w tack.r bold(F) φ) & = bot^p union.sq union.sq.big_(1 <= i <= abs(w)) sem(w^i tack.r φ) \
        sem(w tack.r bold(G) φ) & = top^p inter.sq inter.sq.big_(1 <= i <= abs(w)) sem(w^i tack.r φ)
      $
    ]
  ],
  caption: [Semantics of #fltl4 formulae over a non-empty finite trace $w = w_1 dots w_(abs(w)) ∈ Σ^+$],
) <fig-fltl4-sem>

#definition([Semantics of #fltl4], label: <def:fltl4-sem>)[
  Let $w = w_1 dots w_(abs(w)) ∈ Σ^+$ denote a non-empty finite trace, and let $w^i$
  denote its suffix starting at position $i$. The truth value of an #fltl4 formula
  $φ$ w.r.t. $w$, denoted with $sem(w tack.r φ)$, is given by the function
  $ sem(- tack.r -) : Σ^+ × #fltl4 -> bb(B)_4 $
  which is defined inductively as shown in @fig-fltl4-sem.
]

Where FLTL falls back on $bot$ and $top$ when the trace runs out (@fig-fltl4-sem, cases
$abs(w) = 1$ for the next operators, and the second disjunct of until/release), #fltl4
falls back on the presumable verdicts $bot^p$ and $top^p$ instead. A definitive verdict
is therefore emitted only when the observed prefix alone already settles the formula,
which is what impartiality asks for.

== Monitor as a Mealy machine

For each temporal formula registered to the `monitor` it is then compiled into a Mealy machine.
Our Mealy machine is the 6-tuple  $(S, s_0, Σ, Γ, δ)$:
- $S$ a ﬁnite set of states,
- a start state $s_0 ∈ S$,
- a finite set called the input alphabet Σ,
- Γ is the output alphabet and
- a transition function $delta_4 : Sigma times "LTL" -> bb(B)_4 times "LTL"$

$
  delta_4 : Sigma times "LTL" -> bb(B)_4 times "LTL"
$

#grid(
  columns: (1fr, 1fr),
  column-gutter: 1.5em,
  $
         delta_4 (a, "true") & = (top, "true") \
        delta_4 (a, "false") & = (bot, "false") \
              delta_4 (a, p) & = cases(
                                 (top, "true") & "if " p in a,
                                 (bot, "false") & "else"
                               ) \
          delta_4 (a, not p) & = cases(
                                 (bot, "false") & "if " p in a,
                                 (top, "true") & "else"
                               ) \
     delta_4 (a, phi or psi) & = (v_phi union.sq v_psi, "smplfy" (phi' or psi')) \
    delta_4 (a, phi and psi) & = (v_phi inter.sq v_psi, "smplfy" (phi' and psi'))
  $,
  $
              delta_4 (a, X phi) & = (bot^p, phi) \
    delta_4 (a, overline(X) phi) & = (top^p, phi) \
          delta_4 (a, phi U psi) & = delta_4 (a, psi or (phi and X (phi U psi))) \
          delta_4 (a, phi R psi) & = delta_4 (a, psi and (phi or overline(X) (phi R psi))) \
              delta_4 (a, F phi) & = delta_4 (a, phi or X F phi) \
              delta_4 (a, G phi) & = delta_4 (a, phi and overline(X) G phi)
  $,
)

$
  "smplfy" : "LTL" -> "LTL"
$

= Development overview <sec-dev>

The `monitor` reads a stream of events output by an application and verifies after each new event whether a set of #fltl4 formulae hold.


The `monitor` is a set of  well formed #fltl4 formulae and then compiled into a Mealy machine.
Each event emitted by the software is an input shared to all the compiled Mealy machine declared.

The `monitor` is extended to keep a history of the previous evaluation at each time step, enabling evaluation of the next state by looking at the history of previous computations.

== The input event stream

A finite word $w$ is a finite sequence over the alphabet $Σ = 2^("AP")$.

The monitor will read a letter $x ∈ Σ$ as input, apply it to the word $w$, and evaluate the formulas over it. However, for efficiency, the monitor will save the last state and evaluate the newer input over it.


The rewrite rules implementing `smplfy`, together with proofs of termination and
confluence (modulo the associativity and commutativity of $and$ and $or$), are
given in the section _Canonical simplification `smplfy` as a term rewriting
system_ below.

== Mealy machine

A possible implementation in Haskell will be:
```hs
evlFLTL4 :: Char -> FLTL -> (Truth, FLTL)
evlFLTL4 a TTrue = (Top, TTrue)
evlFLTL4 a FFalse = (Bot, FFalse)
evlFLTL4 a (Prop p)
  | a == p = (Top, TTrue)
  | a /= p = (Bot, FFalse)
evlFLTL4 a (Not (Prop p))
  | a == p = (Bot, FFalse)
  | a /= p = (Top, TTrue)
evlFLTL4 a (l :\/ r) = (vl ⊔ vr, l' :\/ r')
  where
    (vl, l') = evlFLTL4 a l
    (vr, r') = evlFLTL4 a r
evlFLTL4 a (l :/\ r) = (vl ⊓ vr,  l' :/\ r')
  where
    (vl, l') = evlFLTL4 a l
    (vr, r') = evlFLTL4 a r
evlFLTL4 a (X p) = (PBot, p)
evlFLTL4 a (Xweak p) = (PTop, p)
evlFLTL4 a (U p q) = (PTop, q :\/ (p :/\ X (U p q)))
evlFLTL4 a (R p q) = (PTop, q :/\ (p :\/ Xweak (R p q)))
evlFLTL4 a (F p) = evlFLTL4 a (p :\/ X (F p))
evlFLTL4 a (G p) = evlFLTL4 a (p :/\ Xweak (G p))
```

// = Canonical simplification `smplfy` as a term rewriting system <sec-smplfy>

// We realise `smplfy` as a term rewriting system (TRS) $cal(R)$ on `FLTL₄`
// formulae. Reduction drives a formula toward a normal form; we prove that
// $cal(R)$ is _terminating_ and _confluent modulo the associativity and
// commutativity of $and$ and $or$_, so every formula has a unique normal form and
// `smplfy` is a well-defined function.

// Throughout we assume the input is in negation normal form (NNF): $not$ occurs
// only on atomic propositions. This invariant is established by the `nnf` pre-pass
// and preserved by $delta_4$, hence a literal $p$ or $not p$ is treated as an
// atomic constant by $cal(R)$.

// == Rewrite rules

// We split $cal(R) = cal(R)_s union cal(R)_d$ into a _simplification core_
// $cal(R)_s$ (rules 1–24) and an optional _distribution_ layer $cal(R)_d$
// (rules 25–26).

// #grid(
//   columns: (1fr, 1fr),
//   column-gutter: 1.5em,
//   $
//      "true" and phi & -> phi     &  quad (1) \
//      phi and "true" & -> phi     &  quad (2) \
//     "false" and phi & -> "false" &  quad (3) \
//     phi and "false" & -> "false" &  quad (4) \
//         phi and phi & -> phi     &  quad (5) \
//       "true" or phi & -> "true"  &  quad (6) \
//       phi or "true" & -> "true"  &  quad (7) \
//      "false" or phi & -> phi     &  quad (8) \
//      phi or "false" & -> phi     &  quad (9) \
//          phi or phi & -> phi     & quad (10)
//   $,
//   $
//     phi and (phi or psi) & -> phi     & quad (11) \
//     (phi or psi) and phi & -> phi     & quad (12) \
//     phi or (phi and psi) & -> phi     & quad (13) \
//     (phi and psi) or phi & -> phi     & quad (14) \
//                 F "true" & -> "true"  & quad (15) \
//                G "false" & -> "false" & quad (16) \
//             phi U "true" & -> "true"  & quad (17) \
//            phi R "false" & -> "false" & quad (18) \
//            "false" U psi & -> psi     & quad (19) \
//             "true" R psi & -> psi     & quad (20) \
//             "true" U psi & -> F psi   & quad (21) \
//            "false" R psi & -> G psi   & quad (22) \
//                F (F phi) & -> F phi   & quad (23) \
//                G (G phi) & -> G phi   & quad (24)
//   $,
// )

// Rules (11)–(14) are stated up to the commutativity of $and$ and $or$; their
// four mirror-image variants are included. The distribution layer is:

// $
//   phi and (psi or chi) & -> (phi and psi) or (phi and chi) & quad (25) \
//   (phi or psi) and chi & -> (phi and chi) or (psi and chi) & quad (26)
// $

// #block(inset: (left: 0pt))[
//   *Remark (soundness in $bb(B)_4$).* Because $(bb(B)_4, ⊑)$ is a De Morgan but
//   _not_ a Boolean lattice, the complement laws are inadmissible: taking
//   $phi = ⊤ₚ$ gives $phi or not phi = ⊤ₚ ⊔ ⊥ₚ = ⊤ₚ != ⊤$ and
//   $phi and not phi = ⊤ₚ ⊓ ⊥ₚ = ⊥ₚ != ⊥$. Likewise, temporal operators whose
//   constant argument evaluates to a _presumable_ value are left un-folded, since
//   $⊤ₚ, ⊥ₚ$ are not formulae: $sem(w tack.r F "false") = ⊥ₚ != ⊥$ and
//   $sem(w tack.r G "true") = ⊤ₚ != ⊤$, whereas the absorbing cases (15)–(18) do
//   collapse to $"true" slash "false"$. Every rule above was validated against the
//   semantics $sem(-)$ and the step relation $delta_4$.
// ]

// == Mealy machines as a profunctor

// Input and output of the Mealy machine can be preprocessed and postprocessed
// respectively by viewing the machine as a profunctor; properties that depend on
// one another are then combined by profunctor composition.

// === The Mealy bifunctor

// Write $cal(M)(a, b)$ for the set of Mealy machines with input alphabet $a$ and
// output alphabet $b$. It is the carrier of the terminal coalgebra of the functor
// $X |-> (a -> b × X)$, equivalently the final solution of

// $
//   cal(M)(a, b) ≅ a -> (b × cal(M)(a, b)) .
// $

// A monitor for a formula is the element of $cal(M)(Σ, bb(B)_4 × "LTL")$ obtained
// by unfolding the transition $delta_4 : Σ × "LTL" -> bb(B)_4 × "LTL"$ from the
// formula taken as initial state: reading a letter $a ∈ Σ$ returns a verdict in
// $bb(B)_4$ together with the continuation machine that carries the simplified
// residual formula.

// === Profunctor structure

// $cal(M)$ is a profunctor, i.e. a functor

// $
//   cal(M) : bold("Set")^("op") × bold("Set") -> bold("Set"),
// $

// contravariant in the input and covariant in the output. Its action on morphisms
// $f : a' -> a$ and $g : b -> b'$ is the map

// $
//   cal(M)(f, g) : cal(M)(a, b) -> cal(M)(a', b'),
// $

// defined coinductively: it precomposes the input with $f$ and postcomposes the
// output with $g$, recursing on the continuation. Write $partial_m : a -> b$ for
// the _output map_ of a state $m$ — the verdict it emits now, read off the first
// projection of the isomorphism above. On this observable component the action is
// plain pre- and post-composition:

// #align(center, diagram(
//   spacing: (3.6em, 3em),
//   mbox((0, 0), $f$),
//   mbox((1, 0), $m$),
//   mbox((2, 0), $g$),
//   edge((-1, 0), (0, 0), $a'$, "->"),
//   edge((0, 0), (1, 0), $a$, "->"),
//   edge((1, 0), (2, 0), $b$, "->"),
//   edge((2, 0), (3, 0), $b'$, "->"),
//   compbox(((0, 0), (2, 0))),
//   node((1, -0.8), text(fill: gray, size: .82em)[$m' = cal(M)(f,g)(m)$]),
// ))

// The core machine $m$ is bracketed by the pre-adapter $f$ ($=$ `lmap`) and the
// post-adapter $g$ ($=$ `rmap`); the dashed box is the re-typed machine
// $m' = cal(M)(f, g)(m)$, whose output map is $partial_(m') = g ∘ partial_m ∘ f$.
// On a full input $x$ this reads $cal(M)(f, g)(m)(x) = (g(partial_m (f x)),
//   cal(M)(f, g)(m'))$. This is `dimap`. Functoriality gives the profunctor laws

// $
//   cal(M)("id", "id") = "id", quad
//   cal(M)(f ∘ f', g' ∘ g) = cal(M)(f', g') ∘ cal(M)(f, g),
// $

// so re-typing the boundary never alters the state nor the transition $delta_4$.
// The two one-sided actions are the preprocessing and postprocessing maps:

// $
//   "lmap" f = cal(M)(f, "id") quad (f : e -> Σ), quad quad
//   "rmap" g = cal(M)("id", g) quad (g : bb(B)_4 × "LTL" -> r) .
// $

// - $"lmap" f$ _preprocesses_ the input by reindexing a richer event type $e$ onto
//   the letters $a ∈ Σ$ that a formula observes, so one event stream feeds
//   monitors over different sub-alphabets.
// - $"rmap" g$ _postprocesses_ the verdict — projecting the truth value, or
//   applying the Anticipation look-ahead — as a map on outputs that leaves the
//   dynamics untouched.

// === Composition

// The Mealy machines are themselves the morphisms of a category $bold("Mealy")$:
// objects are alphabets, $bold("Mealy")(a, b) = cal(M)(a, b)$, the identity is the
// copy machine $x |-> (x, "id")$, and series composition threads the state of one
// machine into the next. This composition is exactly the profunctor composition,
// given by the coend

// $
//   (cal(M) ∘ cal(M))(a, c) = integral^(b) cal(M)(a, b) × cal(M)(b, c)
//   quad -> quad cal(M)(a, c),
// $

// and it is how _dependent_ properties are wired: when $ψ$ is evaluated on the
// verdict stream of $φ$, the monitor is the composite $m_φ ⨟ m_ψ$, drawn as the
// block diagram

// #align(center, diagram(
//   spacing: (4.5em, 3em),
//   mbox((0, 0), $m_φ$),
//   mbox((1, 0), $m_ψ$),
//   edge((-1, 0), (0, 0), $Σ$, "->"),
//   edge((0, 0), (1, 0), $bb(B)_4$, "->"),
//   edge((1, 0), (2, 0), $c$, "->"),
//   compbox(((0, 0), (1, 0))),
//   node((0.5, -0.9), text(fill: gray, size: .82em)[$m_φ ⨟ m_ψ$]),
// ))

// where the dashed box is the composite, again a single Mealy machine in
// $cal(M)(Σ, c)$. Operationally the two machines run in lockstep on one tick: an
// event $a ∈ Σ$ enters $m_φ$, which emits a verdict $b ∈ bb(B)_4$ and steps to its
// continuation $m_φ'$; that verdict is fed as the input _letter_ of $m_ψ$, which
// emits the final output $c$ and steps to $m_ψ'$; the composite emits $c$ and
// advances to $m_φ' ⨟ m_ψ'$. Its state is therefore the pair
// $(m_φ, m_ψ)$, and on output maps it is the pipeline
// $partial_(m_φ ⨟ m_ψ) = partial_(m_ψ) ∘ partial_(m_φ)$.

// The intermediate alphabet is the _output_ of $m_φ$, not $Σ$: a dependent monitor
// reads the upstream verdict stream. Concretely one takes $m_φ : cal(M)(Σ, bb(B)_4)$
// — the verdict stream of $φ$, obtained from its full monitor by `rmap` $pi_1$ to
// drop the residual formula — and a meta-property $m_ψ : cal(M)(bb(B)_4, c)$ over
// that stream, e.g. _"$φ$'s verdict has stabilised to $⊤ₚ$"_. Because the composite
// is itself an element of $cal(M)(Σ, c)$, it may be re-typed by `lmap`/`rmap` or
// composed again: the construction is closed.

// $bold("Mealy")$ is moreover monoidal under the product of alphabets, with the
// parallel product $cal(M)(a, b) × cal(M)(c, d) -> cal(M)(a × c, b × d)$.
// Precomposing the parallel of two monitors with the diagonal
// $Delta : Σ -> Σ × Σ$ (that is, $"lmap" Delta$) broadcasts a single event to both
// and pairs their verdicts, $lr(chevron.l m_φ, m_ψ chevron.r) : cal(M)(Σ, (bb(B)_4 ×
//     "LTL")^2)$, with output map

// #align(center, diagram(
//   spacing: (4em, 2.4em),
//   node((0, 0), $Delta$),
//   mbox((1, -1), $m_φ$),
//   mbox((1, 1), $m_ψ$),
//   node((2, 0), $(bb(B)_4 × "LTL")^2$),
//   edge((-1, 0), (0, 0), $Σ$, "->"),
//   edge((0, 0), (1, -1), $Σ$, "->"),
//   edge((0, 0), (1, 1), $Σ$, "->"),
//   edge((1, -1), (2, 0), "->"),
//   edge((1, 1), (2, 0), "->"),
//   compbox(((1, -1), (1, 1))),
//   node((1, -1.8), text(fill: gray, size: .82em)[$lr(chevron.l m_φ\, m_ψ chevron.r)$]),
// ))

// This shared-input fan-out underlies a `monitor` assembled from many formulae:
// every event reaches every declared machine, as described in the overview.

#bibliography("refs.bib")
